"""Revision-bound task rehydration and explicit context assembly contracts."""

from .assembly import (
    ContextAssemblyContract,
    build_context_assembly_contract,
    validate_context_assembly_contract,
)
from .budget import (
    ContextBudgetReceipt,
    ContextBudgetSource,
    build_context_budget_receipt,
    validate_context_budget_receipt,
)
from .consumption import (
    MODEL_CONTEXT_CONSUMPTION_RECEIPT_SCHEMA,
    OUTCOME_CONTRIBUTION_NOT_PROVEN,
    PHYSICAL_CONSUMPTION_NOT_PROVEN,
    PHYSICAL_CONSUMPTION_PROVEN,
    build_online_consumption_receipt,
    build_worker_consumption_receipt,
    serialized_package_sha256,
    validate_consumption_receipt,
)
from .context_admission import (
    CONTEXT_ADMISSION_EXPLAINABILITY_CLAIM_CEILING,
    CONTEXT_ADMISSION_EXPLAINABILITY_SCHEMA,
    CONTEXT_ADMISSION_SCHEMA,
    CONTEXT_ADMISSION_TELEMETRY_SCHEMA,
    HIDDEN_RECOVERABLE,
    SEGMENT_CONTRACT_REQUIRED,
    SEGMENT_ERROR,
    SEGMENT_FILE_REFERENCE,
    SEGMENT_RECEIPT,
    SEGMENT_SUMMARY,
    SEGMENT_TEXT,
    SEGMENT_TRUNCATED,
    VISIBLE_NOW,
    AdmissionDecision,
    ContextAdmissionError,
    ContextAdmissionReceipt,
    ContextAdmissionTelemetry,
    ContextSegment,
    admit_artifact,
    build_admission_receipt,
    build_admission_telemetry,
    build_context_admission_explainability_projection,
    decide_visibility,
    recall_hidden_segments,
    restore_visible_text,
    segment_artifact,
)
from .continuity import (
    ContinuityEvent,
    ContinuitySnapshot,
    ResumeContext,
    build_rehydration_projection,
    events_from_attempt_records,
    project,
    resume,
)
from .ports import ContextAssembler, ContextReceiptBuilder, ContinuityEventSource
from .retrieval_hints import (
    CANONICAL_QUERY_EVIDENCE_SCHEMA,
    HINT_ADVISORY,
    RETRIEVAL_HINT_CLAIM_CEILING,
    RETRIEVAL_HINT_OBSERVATION_SCHEMA,
    RETRIEVAL_HINT_SCHEMA,
    RETRIEVAL_HINT_TELEMETRY_SCHEMA,
    apply_hint_observation_envelope,
    bind_retrieval_hints,
    build_hint_observation_envelope,
    build_hint_telemetry,
    compose_hinted_context,
    compose_verified_repository_query_hints,
    seal_retrieval_hint_report,
    validate_hint_observation_envelope,
    validate_hint_telemetry,
    validate_retrieval_hint_evidence,
    validate_retrieval_hint_report,
)
from .runtime_adapter import (
    StatelessContextCoordinator,
    build_runtime_context_payload,
)
from .source_materialization import (
    DIRECT_SLICE,
    NO_SOURCE,
    RAW_SOURCE,
    REDUCED_CAPSULE,
    SOURCE_MATERIALIZATION_CLAIM_CEILING,
    SOURCE_MATERIALIZATION_SCHEMA,
    SOURCE_MATERIALIZATION_STRATEGIES,
    build_source_materialization_projection,
    validate_source_materialization_projection,
)

__all__ = [
    "CONTEXT_ADMISSION_EXPLAINABILITY_CLAIM_CEILING",
    "CONTEXT_ADMISSION_EXPLAINABILITY_SCHEMA",
    "CONTEXT_ADMISSION_SCHEMA",
    "CONTEXT_ADMISSION_TELEMETRY_SCHEMA",
    "DIRECT_SLICE",
    "HIDDEN_RECOVERABLE",
    "MODEL_CONTEXT_CONSUMPTION_RECEIPT_SCHEMA",
    "MODEL_CONTEXT_MARKER",
    "NO_SOURCE",
    "OUTCOME_CONTRIBUTION_NOT_PROVEN",
    "PHYSICAL_CONSUMPTION_NOT_PROVEN",
    "PHYSICAL_CONSUMPTION_PROVEN",
    "RAW_SOURCE",
    "REDUCED_CAPSULE",
    "SEGMENT_CONTRACT_REQUIRED",
    "SEGMENT_ERROR",
    "SEGMENT_FILE_REFERENCE",
    "SEGMENT_RECEIPT",
    "SEGMENT_SUMMARY",
    "SEGMENT_TEXT",
    "SEGMENT_TRUNCATED",
    "SOURCE_MATERIALIZATION_CLAIM_CEILING",
    "SOURCE_MATERIALIZATION_SCHEMA",
    "SOURCE_MATERIALIZATION_STRATEGIES",
    "VISIBLE_NOW",
    "AdmissionDecision",
    "ContextAdmissionError",
    "ContextAdmissionReceipt",
    "ContextAdmissionTelemetry",
    "ContextAssembler",
    "ContextAssemblyContract",
    "ContextBudgetReceipt",
    "ContextBudgetSource",
    "ContextReceiptBuilder",
    "ContextSegment",
    "ContinuityEvent",
    "ContinuityEventSource",
    "ContinuitySnapshot",
    "ResumeContext",
    "StatelessContextCoordinator",
    "admit_artifact",
    "append_model_context_to_prompt",
    "build_admission_receipt",
    "build_admission_telemetry",
    "CANONICAL_QUERY_EVIDENCE_SCHEMA",
    "HINT_ADVISORY",
    "RETRIEVAL_HINT_CLAIM_CEILING",
    "RETRIEVAL_HINT_OBSERVATION_SCHEMA",
    "RETRIEVAL_HINT_SCHEMA",
    "RETRIEVAL_HINT_TELEMETRY_SCHEMA",
    "apply_hint_observation_envelope",
    "bind_retrieval_hints",
    "build_hint_observation_envelope",
    "build_hint_telemetry",
    "compose_hinted_context",
    "compose_verified_repository_query_hints",
    "seal_retrieval_hint_report",
    "validate_hint_observation_envelope",
    "validate_hint_telemetry",
    "validate_retrieval_hint_evidence",
    "validate_retrieval_hint_report",
    "build_context_admission_explainability_projection",
    "build_context_assembly_contract",
    "build_context_budget_receipt",
    "build_online_consumption_receipt",
    "build_online_context_package",
    "build_planner_consumer_context_package",
    "build_rehydration_projection",
    "build_runtime_context_payload",
    "build_source_materialization_projection",
    "build_worker_consumption_receipt",
    "build_worker_context_package",
    "build_worker_context_package_with_admission",
    "decide_visibility",
    "events_from_attempt_records",
    "extract_model_context_from_prompt",
    "project",
    "project_runtime_exports_with_model_context",
    "recall_hidden_segments",
    "restore_visible_text",
    "resume",
    "segment_artifact",
    "serialize_model_context_package",
    "serialized_package_sha256",
    "validate_consumption_receipt",
    "validate_context_assembly_contract",
    "validate_context_budget_receipt",
    "validate_source_materialization_projection",
    "wrap_online_invoker",
]


# consumer_projection pulls in the planner family; resolve its names lazily so
# consumer surfaces (continuity, budget, ...) do not pay for it.
_LAZY_CONSUMER_PROJECTION = frozenset((
    "MODEL_CONTEXT_MARKER",
    "append_model_context_to_prompt",
    "build_online_context_package",
    "build_planner_consumer_context_package",
    "build_worker_context_package",
    "build_worker_context_package_with_admission",
    "extract_model_context_from_prompt",
    "project_runtime_exports_with_model_context",
    "serialize_model_context_package",
    "wrap_online_invoker",
))


def __getattr__(name: str):
    if name in _LAZY_CONSUMER_PROJECTION:
        from . import consumer_projection

        value = getattr(consumer_projection, name)
        globals()[name] = value
        return value
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


def __dir__():
    return sorted(set(globals()) | set(__all__))
